### ISSUE TITLE
Need to print spin configuration snapshots

### ISSUE THREAD

**Issue by shishirkrpandey** [fbuessen/SpinParser#11]
Hello Finn, 
May I know if it is possible to generate spin configurations snapshots at different frequency as well as for the ground state? 

Thanks for your help.

**Comment by fbuessen** [comment]
Hi,
The pseudofermion-FRG algorithm is formulated such that it fundamentally relies on the computation of two-spin correlations. 
Unfortunately, the method is therefore unable to resolve the magnetic order itself -- at least in the sense of observing finite spin expectation values associated with spontaneous symmetry breaking (see also Sec. 2.5.1 of my [PhD thesis](https://kups.ub.uni-koeln.de/9986/) for a comment on symmetry breaking and phase transitions). 
It is, however, possible to resolve two-spin correlations (rather than spin configurations) and visualize them in real space, see the last example plot in the [README.md](https://github.com/fbuessen/SpinParser#evaluate-spinparser-output-and-measurements).
I hope this helps!
